### ISSUE TITLE
Error on training 

### ISSUE THREAD

**Issue by FFrankyy** [Hanjun-Dai/graph_comb_opt#4]
when I enter the command:
./run_nstep_dqn.sh
it returned:

Traceback (most recent call last):
  File "main.py", line 77, in <module>
    api = MvcLib(sys.argv)
  File "/home/fanchangjun/Code/graph_comb_opt/code/s2v_mvc/mvc_lib/mvc_lib.py", line 11, in __init__
    self.lib = ctypes.CDLL('%s/build/dll/libmvc.so' % dir_path)
  File "/home/fanchangjun/anaconda2/lib/python2.7/ctypes/__init__.py", line 366, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/fanchangjun/Code/graph_comb_opt/code/s2v_mvc/mvc_lib/build/dll/libmvc.so: cannot open shared object file: No such file or directory

Do you know the reasons? Thanks!

**Comment by FFrankyy** [comment]
It has been addressed already, thanks！

**Comment by Hanjun-Dai** [comment]
close the issue since it has been resolved.
